name: DSML
channels:
  - conda-forge
  - defaults
channel_priority: strict
dependencies:
  - python=3.13
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - scipy
  - statsmodels
  - jupyterlab
  - notebook
  - ipykernel
  - pytorch
  - torchvision
  - torchaudio
  - xgboost
  - lightgbm
  - catboost
  - tensorflow
  - keras
  - sympy
  - networkx
  - opencv
  - pydantic
  - joblib
  - tqdm
  - plotly
  - pandas-profiling
  - scikit-image
  - pip
  - pip:
    - islp
